services:
  app:
    image: localhost:5000/mobitweb:dev
    build:
      context: Mobit.Web
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Username=mobituser;Password=mobitpass;Database=mobitdb"
      ASPNETCORE_URLS: http://*:80
    ports:
      - "5080:80"          
    depends_on:
      - db
    networks:
      - mobitnet
  db:
    image: localhost:5000/mobitdb:dev
    build:
      context: Database
    ports:
      - "5456:5432"
      #environment:
      #POSTGRES_DB: mobitdb
      #POSTGRES_USER: mobituser
      #POSTGRES_PASSWORD: mobitpass
    networks:
      - mobitnet

networks:
  mobitnet:
    driver: bridge



